import './globals.css'

import {ClerkProvider} from "@clerk/nextjs";
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import React from "react";

const poppins = Poppins({weight: ['300', '700'], subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body suppressHydrationWarning={true} className={poppins.className}>
      {children}
      </body>
      </html>
    </ClerkProvider>
  )
}
